Import start

In [58]:
import pandas as pd
df=pd.read_csv("../data/raw data/Fraudulent_E-Commerce_Transaction_Data.csv")
df2=pd.read_csv("../data/raw data/Fraudulent_E-Commerce_Transaction_Data_2.csv")

In [59]:
df.columns

Index(['Transaction ID', 'Customer ID', 'Transaction Amount',
       'Transaction Date', 'Payment Method', 'Product Category', 'Quantity',
       'Customer Age', 'Customer Location', 'Device Used', 'IP Address',
       'Shipping Address', 'Billing Address', 'Is Fraudulent',
       'Account Age Days', 'Transaction Hour'],
      dtype='str')

In [60]:
df2.columns

Index(['Transaction ID', 'Customer ID', 'Transaction Amount',
       'Transaction Date', 'Payment Method', 'Product Category', 'Quantity',
       'Customer Age', 'Customer Location', 'Device Used', 'IP Address',
       'Shipping Address', 'Billing Address', 'Is Fraudulent',
       'Account Age Days', 'Transaction Hour'],
      dtype='str')

In [61]:
df=pd.concat([df,df2],ignore_index=True)

Checking the data quality

checking the rows and columns

In [62]:
print(df.shape)

(1496586, 16)

In [63]:
print(df.columns)
print(df2.columns)

Index(['Transaction ID', 'Customer ID', 'Transaction Amount',
       'Transaction Date', 'Payment Method', 'Product Category', 'Quantity',
       'Customer Age', 'Customer Location', 'Device Used', 'IP Address',
       'Shipping Address', 'Billing Address', 'Is Fraudulent',
       'Account Age Days', 'Transaction Hour'],
      dtype='str')
Index(['Transaction ID', 'Customer ID', 'Transaction Amount',
       'Transaction Date', 'Payment Method', 'Product Category', 'Quantity',
       'Customer Age', 'Customer Location', 'Device Used', 'IP Address',
       'Shipping Address', 'Billing Address', 'Is Fraudulent',
       'Account Age Days', 'Transaction Hour'],
      dtype='str')

checking datatype

In [64]:
print(df.dtypes)
print(df2.dtypes)

Transaction ID            str
Customer ID               str
Transaction Amount    float64
Transaction Date          str
Payment Method            str
Product Category          str
Quantity                int64
Customer Age            int64
Customer Location         str
Device Used               str
IP Address                str
Shipping Address          str
Billing Address           str
Is Fraudulent           int64
Account Age Days        int64
Transaction Hour        int64
dtype: object
Transaction ID            str
Customer ID               str
Transaction Amount    float64
Transaction Date          str
Payment Method            str
Product Category          str
Quantity                int64
Customer Age            int64
Customer Location         str
Device Used               str
IP Address                str
Shipping Address          str
Billing Address           str
Is Fraudulent           int64
Account Age Days        int64
Transaction Hour        int64
dtype: object

Checking first few row of data frames

In [65]:
df.info

<bound method DataFrame.info of                                Transaction ID  \
0        15d2e414-8735-46fc-9e02-80b472b2580f
1        0bfee1a0-6d5e-40da-a446-d04e73b1b177
2        e588eef4-b754-468e-9d90-d0e0abfc1af0
3        4de46e52-60c3-49d9-be39-636681009789
4        074a76de-fe2d-443e-a00c-f044cdb68e21
...                                       ...
1496581  d8b7171f-bdd9-479c-b98b-396c621aebfe
1496582  0fd12cf3-c641-4499-8de1-15dc4555cb0c
1496583  649680d3-a684-44cb-95bf-9b454c3aa86d
1496584  c10dbb08-28fc-4ec1-9850-d4e98d2b9640
1496585  23e3c107-f2fc-48c2-abbc-7b809bf6f102

                                  Customer ID  Transaction Amount  \
0        d1b87f62-51b2-493b-ad6a-77e0fe13e785               58.09
1        37de64d5-e901-4a56-9ea0-af0c24c069cf              389.96
2        1bac88d6-4b22-409a-a06b-425119c57225              134.19
3        2357c76e-9253-4ceb-b44e-ef4b71cb7d4d              226.17
4        45071bc5-9588-43ea-8093-023caec8ea1c              121.53
...                                       ...                 ...
1496581  98a3d94c-dc9a-4525-b273-e6ffe54cc5a4               53.73
1496582  b3429f52-8b27-46b5-914c-4accd989edb4               47.42
1496583  066e25c9-4420-4224-bc3f-1a462708090e             1045.23
1496584  cde96e9c-f562-4b8c-8fa8-f356f474232b               34.25
1496585  d8d7a64e-8419-4421-910a-a7cf709a900b               85.03

            Transaction Date Payment Method Product Category  Quantity  \
0        2024-02-20 05:58:41  bank transfer      electronics         1
1        2024-02-25 08:09:45     debit card      electronics         2
2        2024-03-18 03:42:55         PayPal    home & garden         2
3        2024-03-16 20:41:31  bank transfer         clothing         5
4        2024-01-15 05:08:17  bank transfer         clothing         2
...                      ...            ...              ...       ...
1496581  2024-01-26 16:25:05         PayPal     toys & games         5
1496582  2024-02-25 17:03:26    credit card         clothing         4
1496583  2024-03-28 23:46:47  bank transfer  health & beauty         1
1496584  2024-02-09 11:29:18     debit card    home & garden         2
1496585  2024-01-23 02:46:52    credit card         clothing         4

         Customer Age  Customer Location Device Used       IP Address  \
0                  17      Amandaborough      tablet   212.195.49.198
1                  40       East Timothy     desktop  208.106.249.121
2                  22         Davismouth      tablet     76.63.88.212
3                  31           Lynnberg     desktop   207.208.171.73
4                  51       South Nicole      tablet   190.172.14.169
...               ...                ...         ...              ...
1496581            32        Rebeccafurt      tablet   173.97.197.128
1496582            41        Nataliefort     desktop    133.222.22.48
1496583             9  East Shannonville      tablet  206.133.237.168
1496584            39        Lake Nicole      mobile   16.204.137.130
1496585            38           Holtport      tablet  116.188.254.162

                                          Shipping Address  \
0                         Unit 8934 Box 0058\nDPO AA 05437
1                  634 May Keys\nPort Cherylview, NV 75063
2          16282 Dana Falls Suite 790\nRothhaven, IL 15564
3           828 Strong Loaf Apt. 646\nNew Joshua, UT 84798
4        29799 Jason Hills Apt. 439\nWest Richardtown, ...
...                                                    ...
1496581                         USNV Clayton\nFPO AE 82639
1496582  9288 Patricia Cape Apt. 527\nMelissaton, IL 38543
1496583  3015 Elizabeth Summit Suite 819\nEast Joelfort...
1496584             531 Brittany Pike\nNew Stacy, OR 87952
1496585           289 Adams Wells\nWest Joeltown, LA 69190

                                           Billing Address  Is Fraudulent  \
0                         Unit 8934 Box 0058\nDPO AA 05437              0
1                  634 May Keys\nPort Cherylview, NV 75063              0
2          16282 Dana Falls Suite 790\nRothhaven, IL 15564              0
3           828 Strong Loaf Apt. 646\nNew Joshua, UT 84798              0
4        29799 Jason Hills Apt. 439\nWest Richardtown, ...              0
...                                                    ...            ...
1496581                         USNV Clayton\nFPO AE 82639              0
1496582  9288 Patricia Cape Apt. 527\nMelissaton, IL 38543              0
1496583  3015 Elizabeth Summit Suite 819\nEast Joelfort...              0
1496584             531 Brittany Pike\nNew Stacy, OR 87952              0
1496585           289 Adams Wells\nWest Joeltown, LA 69190              0

         Account Age Days  Transaction Hour
0                      30                 5
1                      72                 8
2                      63                 3
3                     124                20
4                     158                 5
...                   ...               ...
1496581               363                16
1496582               296                17
1496583               329                23
1496584               347                11
1496585               203                 2

[1496586 rows x 16 columns]>

checking Number of missing values

In [66]:
print(df.isnull().sum())
print(df2.isnull().sum())

Transaction ID        0
Customer ID           0
Transaction Amount    0
Transaction Date      0
Payment Method        0
Product Category      0
Quantity              0
Customer Age          0
Customer Location     0
Device Used           0
IP Address            0
Shipping Address      0
Billing Address       0
Is Fraudulent         0
Account Age Days      0
Transaction Hour      0
dtype: int64
Transaction ID        0
Customer ID           0
Transaction Amount    0
Transaction Date      0
Payment Method        0
Product Category      0
Quantity              0
Customer Age          0
Customer Location     0
Device Used           0
IP Address            0
Shipping Address      0
Billing Address       0
Is Fraudulent         0
Account Age Days      0
Transaction Hour      0
dtype: int64

checking Missing values or duplicate rows

In [67]:
print("Duplicate rows:", df.duplicated().sum())
print("Duplicate rows:", df2.duplicated().sum())

Duplicate rows: 0
Duplicate rows: 0

checking data info

In [68]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 1496586 entries, 0 to 1496585
Data columns (total 16 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   Transaction ID      1496586 non-null  str
 1   Customer ID         1496586 non-null  str
 2   Transaction Amount  1496586 non-null  float64
 3   Transaction Date    1496586 non-null  str
 4   Payment Method      1496586 non-null  str
 5   Product Category    1496586 non-null  str
 6   Quantity            1496586 non-null  int64
 7   Customer Age        1496586 non-null  int64
 8   Customer Location   1496586 non-null  str
 9   Device Used         1496586 non-null  str
 10  IP Address          1496586 non-null  str
 11  Shipping Address    1496586 non-null  str
 12  Billing Address     1496586 non-null  str
 13  Is Fraudulent       1496586 non-null  int64
 14  Account Age Days    1496586 non-null  int64
 15  Transaction Hour    1496586 non-null  int64
dtypes: float64(1), int64(5), str(10)
memory usage: 182.7 MB
None

In [69]:
print(df2.info())

<class 'pandas.DataFrame'>
RangeIndex: 23634 entries, 0 to 23633
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Transaction ID      23634 non-null  str
 1   Customer ID         23634 non-null  str
 2   Transaction Amount  23634 non-null  float64
 3   Transaction Date    23634 non-null  str
 4   Payment Method      23634 non-null  str
 5   Product Category    23634 non-null  str
 6   Quantity            23634 non-null  int64
 7   Customer Age        23634 non-null  int64
 8   Customer Location   23634 non-null  str
 9   Device Used         23634 non-null  str
 10  IP Address          23634 non-null  str
 11  Shipping Address    23634 non-null  str
 12  Billing Address     23634 non-null  str
 13  Is Fraudulent       23634 non-null  int64
 14  Account Age Days    23634 non-null  int64
 15  Transaction Hour    23634 non-null  int64
dtypes: float64(1), int64(5), str(10)
memory usage: 2.9 MB
None

checking payment method

In [70]:
print(df["Payment Method"].value_counts())

Payment Method
credit card      374352
debit card       374229
bank transfer    374138
PayPal           373867
Name: count, dtype: int64

checking product category

In [71]:

print(df["Product Category"].value_counts())

Product Category
electronics        300042
health & beauty    300038
clothing           299018
toys & games       298996
home & garden      298492
Name: count, dtype: int64

checking device use

In [72]:
print(df["Device Used"].value_counts())

Device Used
mobile     499624
tablet     498768
desktop    498194
Name: count, dtype: int64

In [73]:
print(df["Is Fraudulent"].value_counts())

Is Fraudulent
0    1421526
1      75060
Name: count, dtype: int64

In [74]:
df.describe()

,Transaction Amount,Quantity,Customer Age,Is Fraudulent,Account Age Days,Transaction Hour
count,1.496586e+06,1.496586e+06,1.496586e+06,1.496586e+06,1.496586e+06,1.496586e+06
mean,2.268093e+02,3.000235e+00,3.451284e+01,5.015415e-02,1.796308e+02,1.128663e+01
std,2.705831e+02,1.414814e+00,1.000323e+01,2.182630e-01,1.068726e+02,6.976067e+00
min,1.000000e+01,1.000000e+00,-1.600000e+01,0.000000e+00,1.000000e+00,0.000000e+00
25%,6.862000e+01,2.000000e+00,2.800000e+01,0.000000e+00,8.600000e+01,5.000000e+00
50%,1.517600e+02,3.000000e+00,3.500000e+01,0.000000e+00,1.790000e+02,1.100000e+01
75%,2.960500e+02,4.000000e+00,4.100000e+01,0.000000e+00,2.720000e+02,1.700000e+01
max,1.270175e+04,5.000000e+00,8.600000e+01,1.000000e+00,3.650000e+02,2.300000e+01

In [75]:
df["Transaction Date"] = pd.to_datetime(
    df["Transaction Date"],
    errors="coerce")
df2["Transaction Date"] = pd.to_datetime(
    df["Transaction Date"],
    errors="coerce")

In [76]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1496586 entries, 0 to 1496585
Data columns (total 16 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   Transaction ID      1496586 non-null  str
 1   Customer ID         1496586 non-null  str
 2   Transaction Amount  1496586 non-null  float64
 3   Transaction Date    1496586 non-null  datetime64[us]
 4   Payment Method      1496586 non-null  str
 5   Product Category    1496586 non-null  str
 6   Quantity            1496586 non-null  int64
 7   Customer Age        1496586 non-null  int64
 8   Customer Location   1496586 non-null  str
 9   Device Used         1496586 non-null  str
 10  IP Address          1496586 non-null  str
 11  Shipping Address    1496586 non-null  str
 12  Billing Address     1496586 non-null  str
 13  Is Fraudulent       1496586 non-null  int64
 14  Account Age Days    1496586 non-null  int64
 15  Transaction Hour    1496586 non-null  int64
dtypes: datetime64[us](1), float64(1), int64(5), str(9)
memory usage: 182.7 MB

In [77]:
df["Transaction Date"].isnull().sum()
df2["Transaction Date"].isnull().sum()

np.int64(0)

In [78]:
df[df["Transaction Amount"] < 0]

Empty DataFrame
Columns: [Transaction ID, Customer ID, Transaction Amount, Transaction Date, Payment Method, Product Category, Quantity, Customer Age, Customer Location, Device Used, IP Address, Shipping Address, Billing Address, Is Fraudulent, Account Age Days, Transaction Hour]
Index: []

In [79]:
df[df["Quantity"] <= 0]

Empty DataFrame
Columns: [Transaction ID, Customer ID, Transaction Amount, Transaction Date, Payment Method, Product Category, Quantity, Customer Age, Customer Location, Device Used, IP Address, Shipping Address, Billing Address, Is Fraudulent, Account Age Days, Transaction Hour]
Index: []

In [80]:
df[(df["Customer Age"] < 0) | (df["Customer Age"] > 100)]

,Transaction ID,Customer ID,Transaction Amount,Transaction Date,Payment Method,Product Category,Quantity,Customer Age,Customer Location,Device Used,IP Address,Shipping Address,Billing Address,Is Fraudulent,Account Age Days,Transaction Hour
3193,ed992d5a-4a28-45bf-bdaf-f7e737f5c8f9,4e87ec9a-7bea-4ddf-b0e6-569332c1854b,65.50,2024-02-23 20:38:18,PayPal,home & garden,1,-3,Huntburgh,tablet,99.113.154.217,USNS Brock\nFPO AP 16205,USNS Brock\nFPO AP 16205,0,229,20
7078,1fe82cb8-26a3-464c-908d-415dff80bbe4,7ff030fb-54a5-4764-8b83-108ea2b25651,61.81,2024-01-07 13:48:25,bank transfer,health & beauty,1,-4,Jasminemouth,mobile,199.127.77.116,"4850 Ingram Keys\nEast Amandafurt, WY 22396","518 Craig Parkway Suite 951\nGregoryville, RI ...",0,124,13
8213,a630b0a7-c5ee-4f0f-97f6-4aa3fc2a2d5b,ccabf552-f2ac-43c4-b723-e6bd20de72ca,411.15,2024-02-28 11:42:30,debit card,electronics,4,-4,North Courtney,tablet,37.90.116.230,"4836 Jeremy Shore\nPort Bradleyside, LA 11193","4836 Jeremy Shore\nPort Bradleyside, LA 11193",0,346,11
10110,c5a1ea50-26b3-472d-8729-acc11199bcba,020b3035-d0e9-4a3f-8bd6-a4affe5761f7,241.26,2024-03-03 01:11:29,PayPal,home & garden,3,-1,South Shaneborough,desktop,190.193.198.116,"1828 Manuel Wall Suite 113\nWebbstad, AZ 62193","94016 Hunter Cliff Suite 042\nJimenezfurt, CT ...",0,71,1
13830,6f612d29-c434-4319-bcab-698a076a4122,03121780-f53c-4aa8-ab7d-97a1482518d7,138.22,2024-02-06 19:05:39,credit card,toys & games,2,-1,Holderbury,desktop,7.110.93.93,"7311 Tara Prairie\nSouth Omarmouth, SD 42497","7311 Tara Prairie\nSouth Omarmouth, SD 42497",0,209,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1445037,9332dd89-50cf-4f35-a55d-0524a5f5f475,730ad608-2578-49ec-9cad-91cf3261930d,231.58,2024-01-28 17:44:18,PayPal,electronics,4,-6,Brianside,mobile,157.239.157.148,"0712 Newman Trail Suite 765\nNew Jennachester,...","0712 Newman Trail Suite 765\nNew Jennachester,...",0,252,17
1456987,9aead068-ed3f-444e-9d3d-9de0b6dc68d9,2aa3217b-0a03-440b-a18d-bbf0dadb11c6,30.75,2024-03-26 04:19:39,PayPal,clothing,3,-3,Josephport,tablet,202.246.88.140,"11440 Jesse Via Apt. 329\nVegaview, VI 49897","11440 Jesse Via Apt. 329\nVegaview, VI 49897",0,27,4
1461579,09bdead0-7df1-43ae-8437-5af84a24bdc3,230bf5c8-0516-4295-939e-83f2a4c71d38,129.69,2024-01-30 00:04:35,debit card,electronics,2,-4,New Elizabeth,desktop,205.120.55.253,"679 Megan Dale Suite 663\nNorth Kaitlynville, ...","679 Megan Dale Suite 663\nNorth Kaitlynville, ...",0,152,0
1469645,2f2ad3d5-895f-4c7c-b636-e9e61d6a42b3,1cdabd19-8d8b-4f3b-865d-bf9216334af1,103.11,2024-02-09 14:35:47,bank transfer,toys & games,3,-2,Kristieton,desktop,86.241.107.190,"03862 Emily Hill\nPaulburgh, ID 06455","03862 Emily Hill\nPaulburgh, ID 06455",0,122,14
1485871,7fab7db0-e4d2-4b51-98f3-bb17b5153224,e0345e5b-d91c-4851-b9ae-5170c9b8e7cc,190.76,2024-01-05 15:02:49,PayPal,health & beauty,3,-2,Cohenmouth,desktop,134.95.208.38,Unit 2353 Box 9474\nDPO AA 79121,Unit 2353 Box 9474\nDPO AA 79121,0,253,15

In [81]:
df[(df["Transaction Hour"] < 0) | (df["Transaction Hour"] > 23)]

Empty DataFrame
Columns: [Transaction ID, Customer ID, Transaction Amount, Transaction Date, Payment Method, Product Category, Quantity, Customer Age, Customer Location, Device Used, IP Address, Shipping Address, Billing Address, Is Fraudulent, Account Age Days, Transaction Hour]
Index: []

In [82]:
df[df["Account Age Days"] < 0]

Empty DataFrame
Columns: [Transaction ID, Customer ID, Transaction Amount, Transaction Date, Payment Method, Product Category, Quantity, Customer Age, Customer Location, Device Used, IP Address, Shipping Address, Billing Address, Is Fraudulent, Account Age Days, Transaction Hour]
Index: []

In [83]:
print(df["Shipping Address"].iloc[0])

Unit 8934 Box 0058
DPO AA 05437

In [84]:
df["Shipping Address"] = (
    df["Shipping Address"]
    .str.replace("\n", " ", regex=False)
    .str.strip()
)

In [85]:
df["Billing Address"] = (
    df["Billing Address"]
    .str.replace("\n", " ", regex=False)
    .str.strip()
)

In [86]:
text_columns = [
    "Payment Method",
    "Product Category",
    "Customer Location",
    "Device Used"
]

for col in text_columns:
    df[col] = df[col].str.strip().str.lower()

In [87]:
for col in text_columns:
    print("\n", col)
    print(df[col].unique())

 Payment Method
<StringArray>
['bank transfer', 'debit card', 'paypal', 'credit card']
Length: 4, dtype: str

 Product Category
<StringArray>
['electronics', 'home & garden', 'clothing', 'toys & games',
 'health & beauty']
Length: 5, dtype: str

 Customer Location
<StringArray>
[       'amandaborough',         'east timothy',           'davismouth',
             'lynnberg',         'south nicole',         'herreramouth',
            'ramosfort',           'port emily',           'carneyfurt',
           'brockburgh',
 ...
      'lake masonhaven',      'east carlymouth',      'lake brentville',
       'east lydiastad',         'west tomfurt',   'north savannahfort',
     'new rachaelmouth',     'south mathewfurt', 'north lindseyborough',
         'east ianstad']
Length: 99412, dtype: str

 Device Used
<StringArray>
['tablet', 'desktop', 'mobile']
Length: 3, dtype: str

In [88]:
import ipaddress

def valid_ip(ip):
    try:
        ipaddress.ip_address(ip)
        return True
    except:
        return False

df["Valid IP"] = df["IP Address"].apply(valid_ip)

df["Valid IP"].value_counts()

Valid IP
True    1496586
Name: count, dtype: int64

In [89]:
df.drop(columns=["Valid IP"], inplace=True)

checking billing address same as shipping address

In [90]:
df["Address Mismatch"] = (
    df["Shipping Address"] != df["Billing Address"]
)
df["Address Mismatch"].value_counts()

Address Mismatch
False    1346721
True      149865
Name: count, dtype: int64

In [91]:
df["Calculated Hour"] = df["Transaction Date"].dt.hour

In [92]:
(df["Calculated Hour"] != df["Transaction Hour"]).sum()

np.int64(28978)

In [93]:
df.duplicated().sum()
df["Transaction ID"].duplicated().sum()
df[df["Transaction ID"].duplicated(keep=False)].sort_values("Transaction ID")

Empty DataFrame
Columns: [Transaction ID, Customer ID, Transaction Amount, Transaction Date, Payment Method, Product Category, Quantity, Customer Age, Customer Location, Device Used, IP Address, Shipping Address, Billing Address, Is Fraudulent, Account Age Days, Transaction Hour, Address Mismatch, Calculated Hour]
Index: []

In [94]:
df["Is Fraudulent"].value_counts()

Is Fraudulent
0    1421526
1      75060
Name: count, dtype: int64

In [95]:
df["Is Fraudulent"].value_counts(normalize=True) * 100

Is Fraudulent
0    94.984585
1     5.015415
Name: proportion, dtype: float64

In [96]:
(df["Customer Age"] < 0).sum()

np.int64(259)

In [97]:
df.loc[df["Customer Age"] < 0, "Customer Age"] = pd.NA

In [98]:
median_age = df["Customer Age"].median()

In [99]:
df["Customer Age"] = df["Customer Age"].fillna(median_age)

In [100]:
df

,Transaction ID,Customer ID,Transaction Amount,Transaction Date,Payment Method,Product Category,Quantity,Customer Age,Customer Location,Device Used,IP Address,Shipping Address,Billing Address,Is Fraudulent,Account Age Days,Transaction Hour,Address Mismatch,Calculated Hour
0,15d2e414-8735-46fc-9e02-80b472b2580f,d1b87f62-51b2-493b-ad6a-77e0fe13e785,58.09,2024-02-20 05:58:41,bank transfer,electronics,1,17.0,amandaborough,tablet,212.195.49.198,Unit 8934 Box 0058 DPO AA 05437,Unit 8934 Box 0058 DPO AA 05437,0,30,5,False,5
1,0bfee1a0-6d5e-40da-a446-d04e73b1b177,37de64d5-e901-4a56-9ea0-af0c24c069cf,389.96,2024-02-25 08:09:45,debit card,electronics,2,40.0,east timothy,desktop,208.106.249.121,"634 May Keys Port Cherylview, NV 75063","634 May Keys Port Cherylview, NV 75063",0,72,8,False,8
2,e588eef4-b754-468e-9d90-d0e0abfc1af0,1bac88d6-4b22-409a-a06b-425119c57225,134.19,2024-03-18 03:42:55,paypal,home & garden,2,22.0,davismouth,tablet,76.63.88.212,"16282 Dana Falls Suite 790 Rothhaven, IL 15564","16282 Dana Falls Suite 790 Rothhaven, IL 15564",0,63,3,False,3
3,4de46e52-60c3-49d9-be39-636681009789,2357c76e-9253-4ceb-b44e-ef4b71cb7d4d,226.17,2024-03-16 20:41:31,bank transfer,clothing,5,31.0,lynnberg,desktop,207.208.171.73,"828 Strong Loaf Apt. 646 New Joshua, UT 84798","828 Strong Loaf Apt. 646 New Joshua, UT 84798",0,124,20,False,20
4,074a76de-fe2d-443e-a00c-f044cdb68e21,45071bc5-9588-43ea-8093-023caec8ea1c,121.53,2024-01-15 05:08:17,bank transfer,clothing,2,51.0,south nicole,tablet,190.172.14.169,"29799 Jason Hills Apt. 439 West Richardtown, O...","29799 Jason Hills Apt. 439 West Richardtown, O...",0,158,5,False,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1496581,d8b7171f-bdd9-479c-b98b-396c621aebfe,98a3d94c-dc9a-4525-b273-e6ffe54cc5a4,53.73,2024-01-26 16:25:05,paypal,toys & games,5,32.0,rebeccafurt,tablet,173.97.197.128,USNV Clayton FPO AE 82639,USNV Clayton FPO AE 82639,0,363,16,False,16
1496582,0fd12cf3-c641-4499-8de1-15dc4555cb0c,b3429f52-8b27-46b5-914c-4accd989edb4,47.42,2024-02-25 17:03:26,credit card,clothing,4,41.0,nataliefort,desktop,133.222.22.48,"9288 Patricia Cape Apt. 527 Melissaton, IL 38543","9288 Patricia Cape Apt. 527 Melissaton, IL 38543",0,296,17,False,17
1496583,649680d3-a684-44cb-95bf-9b454c3aa86d,066e25c9-4420-4224-bc3f-1a462708090e,1045.23,2024-03-28 23:46:47,bank transfer,health & beauty,1,9.0,east shannonville,tablet,206.133.237.168,"3015 Elizabeth Summit Suite 819 East Joelfort,...","3015 Elizabeth Summit Suite 819 East Joelfort,...",0,329,23,False,23
1496584,c10dbb08-28fc-4ec1-9850-d4e98d2b9640,cde96e9c-f562-4b8c-8fa8-f356f474232b,34.25,2024-02-09 11:29:18,debit card,home & garden,2,39.0,lake nicole,mobile,16.204.137.130,"531 Brittany Pike New Stacy, OR 87952","531 Brittany Pike New Stacy, OR 87952",0,347,11,False,11
1496585,23e3c107-f2fc-48c2-abbc-7b809bf6f102,d8d7a64e-8419-4421-910a-a7cf709a900b,85.03,2024-01-23 02:46:52,credit card,clothing,4,38.0,holtport,tablet,116.188.254.162,"289 Adams Wells West Joeltown, LA 69190","289 Adams Wells West Joeltown, LA 69190",0,203,2,False,2

In [101]:
df.to_csv("Cleaned_Data.csv",index=False)